backend:
  name: github
  repo: YuliCenteno/Estudio-Delta-Iuris # Nombre exacto de tu repositorio en GitHub
  branch: main
  base_url: https://silly-kleicha-bf6d69.netlify.app
  auth_endpoint: ""

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Artículos / Novedades"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "description", widget: "text", required: false }
      - { label: "Imagen de portada", name: "image", widget: "image", required: false }
      - { label: "Cuerpo del artículo", name: "body", widget: "markdown" }